# fly.toml app configuration file generated for d1r0l-fso-phonebook on 2023-06-09T21:39:16+04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "d1r0l-fso-phonebook"
primary_region = "otp"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
